# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NasaApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NasaApp
  pod 'R.swift', :inhibit_warnings => true
  pod 'SwiftLint'
  
  pod 'RxCocoa', '5.1.0', :inhibit_warnings => true
  pod 'RxDataSources', '4.0.1'
  pod 'RxGesture', '3.0.1'
  pod 'RxSwift', '5.1.0'
  pod 'RxViewController', '1.0.0'
  
  pod 'SDWebImage', '~> 5.0'
  pod 'SwiftInfiniteScrollView'

end

target 'NasaAppTests' do
  # Pods used by all test targets
  pod 'RxSwift', '5.1.0'
  pod 'RxCocoa', '5.1.0', :inhibit_warnings => true
  pod 'RxTest', '5.0.1'
  pod 'RxBlocking', '5.0.1'
end
