# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NasaApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NasaApp
  pod 'R.swift', :inhibit_warnings => true
  pod 'SwiftLint'
  pod 'RxCocoa', '5.1.0', :inhibit_warnings => true
  pod 'RxDataSources', '4.0.1'
  pod 'RxGesture', '3.0.1'
  pod 'RxSwift', '5.1.0'

end
